apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slurm-operator-crds
  namespace: argocd
spec:
  project: default
  source:
    chart: slurm-operator-crds
    repoURL: ghcr.io/slinkyproject/charts
    targetRevision: "0.4.0"
  destination:
    server: https://kubernetes.default.svc
    namespace: slinky
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
