{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- /* https://github.com/helm/helm-www/issues/1259 */}}
{{- $secretName := include "slurm.authSlurmRef.name" . -}}
{{- $secret := lookup "v1" "Secret" (include "slurm.namespace" .) $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slurm.authSlurmRef.name" . }}
  namespace: {{ include "slurm.namespace" . }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "slurm.authSlurmRef.key" . }}: {{ randAscii 1024 | b64enc }}
immutable: true
{{- end }}{{- /* if not $secret */}}
