annotations:
  license: Apache-2.0
apiVersion: v2
appVersion: "25.05"
description: Slurm Metrics Prometheus Exporter
home: https://slinky.schedmd.com/
icon: https://github.com/SlinkyProject/docs/blob/main/docs/_static/images/slurm-square-500.png
kubeVersion: '>= 1.29'
maintainers:
- email: slinky@schedmd.com
  name: SchedMD LLC.
  url: https://support.schedmd.com/
name: slurm-exporter
sources:
- https://github.com/SlinkyProject/slurm-exporter
type: application
version: 0.4.0
