{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- range $key, $loginset := $.Values.loginsets -}}
{{- if $loginset.enabled }}
{{- $name := printf "%s-%s" (include "slurm.login.name" $) $key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-sssd-conf
  namespace: {{ include "slurm.namespace" $ }}
  labels:
    loginset.slinky.slurm.net/name: {{ $name }}
    {{- include "slurm.labels" $ | nindent 4 }}
type: Opaque
stringData:
  sssd.conf: |
    {{- required "sssdConf is required" $loginset.sssdConf | nindent 4 }}
{{- end }}{{- /* $loginset.enabled */}}
{{- end }}{{- /* range $loginset := $.Values.loginsets */}}
